### ISSUE TITLE
Update Wiki Entry Crafting Basics

### ISSUE THREAD

**Issue by eglische** [salutesh/DayZ-Expansion-Scripts#1]
**Crafting Basics:**

- How to Start

Start a base with a kit, it is used to place the object in the world. 
There are Flag Kit, Wall Kit, Floor Kit, Ramp Kit and Stair Kit. Either of those may have variants, such as Doors, gates etc.
To choose what you are going to build, like in case of a wall if you want windows, or a door, after you placed the object with the wall kit , fill the items necessary into the foundation (TAB, works just like a tent i.e.). Then, you use a hammer to build it up, it will give you the option to change recipe by clicking left mouse button, or to build it, by holding the left mouse button. So, if you decide to build a door, you just switch the recipes until you see what you want to build. If you don’t have an option to build further, than that means either your tool is destroyed, or there is a lack of building materials. 
After choosing a placement for what you want to build (left mouse), you need to fill the item slots on the created slot with Lumber (3m), Nails and Wooden Boards/Planks. (10 Lumber, 30 Nails, 20 Boards, depends on the construction and settings of the server of course).
It is advisable to have the materials behind you, when building walls, as setting the foundation may make it that you can’t pass over the building area. Face the item you are constructing to get the prompt to build it up, you may need to approach it from the other side if nothing shows up.

- Where to get the Materials

To get the Lumber, Boards, you need to chop down a tree with an axe, then you saw it to size with a hacksaw or a wood saw. The maintain your tools, it’s advised to carry a sharpening stone. Duct tape also works to fix some tools, not all. Nails can be found in industrial Spots, or Farms. Sometimes even dropped on Zombies (always check zombies for Food, Code locks and other items).
Secure your base with a flag pole, it serves as protection against tearing down your base from enemies, after setting a pole, nobody but those listed in the deed (press B, Territory, there under Members)

Building Kits			-	2x Sticks 1x Rag (some servers need only 1 Sticks and 1 Rag)
You toggle between the Kit Variants with your left mouse button.

- Quick tipps:

Press X to enable/disable quick snapping
Rotate the Object using your mouse wheel
Dismantle the Building Parts with a Hand Axe

There are youtube videos to see on the topic as well:
https://www.youtube.com/watch?v=AeClmGBnH5E

Happy to help out if you want it refined, you find me in the expansion discord under the name TECorp.|Yeti

**Comment by LieutenantMaster** [comment]
Thank you for the help, I will use parts of your suggestions to improve/add more content in the wiki <3
