### ISSUE TITLE
helicopters spawn upside down after a server restart

### ISSUE THREAD

**Issue by solracph** [salutesh/DayZ-Expansion-Scripts#11]
Installed version 1.4.1114 Sep 24
![Screenshot 2020-09-28 143748](https://user-images.githubusercontent.com/7564025/94472064-3291ba00-0198-11eb-936c-32534a43dc45.png)

**Comment by favimaverick** [comment]
Please Fix this issue it's a great mod but this problem takes the experience of Game down and need to be fixed soon

**Comment by solracph** [comment]
Yes, helicopters are one of the most interesting things that this mod has but with the latest updates they are broken
