### ISSUE TITLE
Sorry! your comment makes no sense!!!!

### ISSUE THREAD

**Issue by neil501** [salutesh/DayZ-Expansion-Scripts#13]
You wrote: "To fix this issue, make sure to have the 4 mods listed from above and you are launching CF and Community Online tool without the EXP tag as explained in step 8"

Hmm Step 8? You ONLY POSTED 5 STEPS!!!!!!!  LOL!!!!! OK!!!! Try to see this from readers/players point of view.
  How can anyone understand a comment that tells the reader the solution is on page 8 when the book is 5 pages long? Can you understand this issue from my point? Please! Can you please explain step 8 here? Since you left it out of the 5 steps you wrote PLEASE????? Your comment makes no sense and this is the EXACT issue im having with your mod. please can you just explain it?

**Comment by LieutenantMaster** [comment]
Hello !

Sorry for the time to comeback to you, I don't get any notifications when someone write something here for some reasons.

This was a mistake from me, the old tutorial had more steps to explain the same process. The error you have is only occuring when the game is not loading Expansion (explaining why it can't find a expansion function).

The mistake on the tutorial have been fixed.
