### ISSUE TITLE
Server Crash: Entity is already deleted (error)

### ISSUE THREAD

**Issue by carvsdriver** [salutesh/DayZ-Expansion-Scripts#14]
Posted this over on the steam community forum.  I'm seeing a server crash every few hours and this is the error being logged.  The entity ID changes for each crash, but the error is the same.    I'm also running the Airdrop-Upgraded mod if that makes a difference (I've also temporarily disabled that mode in case it is presenting a conflict).

Entity is already deleted
Class: 'ExpansionAirdropContainerBase'
Entity id:3065130

Function: 'OnUpdate'
Stack trace:
DayZExpansion/Scripts/4_World/dayzexpansion\entities\systems\airdrop\expansionairdropcontainerbase.c:195
scripts/3_Game/dayzgame.c:2344
DayZExpansion/Scripts/3_Game/dayzexpansion\classes\dayzgame.c:250

**Comment by carvsdriver** [comment]
Error persists without the Airdop-Upgraded mod running.

**Comment by carvsdriver** [comment]
So, is this resolved in an update or just being closed without resolution?

**Comment by LieutenantMaster** [comment]
We have a potential fix for this issue, however due to the lack of testers and time we won't be able to confirm to have fixed for good this issue.

**Comment by carvsdriver** [comment]
Thanks a lot!  Appreciated the updated information.  I'd be happy to help test on my server if needed.

**Comment by LieutenantMaster** [comment]
Since DayZ 1.10 will release tomorrow I think you won't have to wait much more longer to know :b 

Also, we will start communicating about the expansion update later today on our discord and on steam forums about what will change for server hosters and what to do so stay up to date ;)

**Comment by carvsdriver** [comment]
Fair enough.  Thanks again for the response.

**Comment by carvsdriver** [comment]
Can confirm, this seems to be fixed.   Been running for a few hours today with no errors on 1.10 and the updated expansion.  Thanks for all you guys do.

-Pickles/carvsdriver

**Comment by carvsdriver** [comment]
SPoke too soon ...

------------------------------------
WIN-79KRHEUFR8M, 19.11 2020 11:07:07
Entity is already deleted
Class:      'ExpansionAirdropContainerBase'
Entity id:2975253

Function: 'OnUpdate'
Stack trace:
DayZExpansion/Scripts/4_World/dayzexpansion\entities\systems\airdrop\expansionairdropcontainerbase.c:204
scripts/3_Game/dayzgame.c:2331
DayZExpansion/Core/3_Game/dayzexpansion_core\dayzgame.c:203

Runtime mode
CLI params: port 7115 dayzserver DayZServer.exe scrAllowFileWrite  profiles Admin config Admin\serverDZ.cfg name Admin dologs  config pillowFights.cfg mod @CF;@Community-Online-Tools;@DayZ-Expansion-;@DayZ-Expansion-Core-;@DayZ-Expansion-Licensed-;@DayZ-Expansion-Vehicles-;@VanillaPlusPlusMap;@GoreZ;@CannabisPlus;@FlipTransport;@TraderFixesAndFeatures;@Notes;@ReduceGloveAndShoeDmg;@BuildAnywhere_v3;@Seeds Dupe Fix;@Trolley Kart;@WindstridesClothingPack;@SlowerMetabolism;@Saline Bag+;@[CrSk] BMW 525i E34;@Trader Wallet;@BaseBuildingPlus;@MuchStuffPack;@Banking;@Trader; servermod @FixVehiclePositions;@NoExplodingHelis;@NoCollisionDamageIfEngineOff;
