### ISSUE TITLE
[DeerIsland] - Hosted server - Server crash at start

### ISSUE THREAD

**Issue by stephanepapin** [salutesh/DayZ-Expansion-Scripts#15]
Hi
**Kind of Issue ** : server crash at start, not visible from DayZ Launcher (standard). mdump generated
Logs files.
**Map :** Expansion DeerIsland
**Server :** Hosted / host.unlimited
**Address :** 88.218.227.8
**Port :** 47854
**Password**: no
**Mods :** @CF;@Community-Online-Tools;@DayZ-Expansion-;@DayZ-Expansion-Licensed-;@DayZ-Expansion-Vehicles-;@DayZ-Expansion-Core-
**Keys** : Expansion.bikey / dayz.bikey / Jacob_Mango_V3.bikey

[script_2020-11-20_08-51-36.log](https://github.com/salutesh/DayZ-Expansion-Scripts/files/5572062/script_2020-11-20_08-51-36.log)
[server_console.log](https://github.com/salutesh/DayZ-Expansion-Scripts/files/5572063/server_console.log)

[DayZServer_x64_2020-11-20_08-51-29.RPT.TXT](https://github.com/salutesh/DayZ-Expansion-Scripts/files/5572072/DayZServer_x64_2020-11-20_08-51-29.RPT.TXT)
[DayZServer_x64_2020-11-20_08-51-29_2020-11-20_08-51-58.mdmp.txt](https://github.com/salutesh/DayZ-Expansion-Scripts/files/5572074/DayZServer_x64_2020-11-20_08-51-29_2020-11-20_08-51-58.mdmp.txt)

**Comment by stephanepapin** [comment]
Server reset, I'm retrying one more time.

**Comment by stephanepapin** [comment]
2nd fail.
[DayZServer_x64_2020-11-20_10-58-40_2020-11-20_10-59-08.mdmp.txt](https://github.com/salutesh/DayZ-Expansion-Scripts/files/5572752/DayZServer_x64_2020-11-20_10-58-40_2020-11-20_10-59-08.mdmp.txt)
[script_2020-11-20_10-58-48.log](https://github.com/salutesh/DayZ-Expansion-Scripts/files/5572753/script_2020-11-20_10-58-48.log)
[server_console.log](https://github.com/salutesh/DayZ-Expansion-Scripts/files/5572754/server_console.log)
[DayZServer_x64_2020-11-20_10-58-40.RPT.txt](https://github.com/salutesh/DayZ-Expansion-Scripts/files/5572755/DayZServer_x64_2020-11-20_10-58-40.RPT.txt)

**Comment by RC-Robio** [comment]
I don't see @deerisle in your mod line. 
ex: -mod=@CF;@Community-Online-Tools;@DayZ-Expansion-;@DayZ-Expansion-Licensed-;@DayZ-Expansion-Vehicles-;@DayZ-Expansion-Core-;@Deerisle

**Comment by stephanepapin** [comment]
> I don't see @deerisle in your mod line.
> ex: -mod=@cf;@Community-Online-Tools;@DayZ-Expansion-;@DayZ-Expansion-Licensed-;@DayZ-Expansion-Vehicles-;@DayZ-Expansion-Core-;@Deerisle

Hi, damned, bad GUI for hosted server I'm testing, didn't save my parameters.
I'm currently reset my test serve and deploying Expansion+DeeIsland.
I will give you feedback.

**Comment by stephanepapin** [comment]
From fresh server :
Mods Order : @DeerIsle;@CF;@Community-Online-Tools;@DayZ-Expansion-;@DayZ-Expansion-Licensed-;@DayZ-Expansion-Core-;@DayZ-Expansion-Vehicles-
Key : Expansion.bikey / dayz.bikey / Jacob_Mango_V3.bikey / deerisle42b

Server seem running, but no way to connect : return to mains screen without error messages
[server_console.log](https://github.com/salutesh/DayZ-Expansion-Scripts/files/5577836/server_console.log)
[DayZServer_x64_2020-11-21_15-53-43.RPT.txt](https://github.com/salutesh/DayZ-Expansion-Scripts/files/5577838/DayZServer_x64_2020-11-21_15-53-43.RPT.txt)
[script_2020-11-21_15-53-48.log](https://github.com/salutesh/DayZ-Expansion-Scripts/files/5577839/script_2020-11-21_15-53-48.log)

**Comment by RC-Robio** [comment]
First loading of server can take longer. Did you give it time? Whats the server name or ip and I'll try to jump in to see if I can connect.

**Comment by stephanepapin** [comment]
> First loading of server can take longer. Did you give it time? Whats the server name or ip and I'll try to jump in to see if I can connect.
> 
> Post your logs to pastebin.com please.

Server : 88.218.227.8:47854 ([FR]-[PVE]-[DeerIsland]-[TEST]-Les Vieux Crevards n°2)

Server crash one more time, i've stop, change mod orders and restarted.

**Comment by stephanepapin** [comment]
logs : 
https://pastebin.com/WpEZFkJC

**Comment by RC-Robio** [comment]
I'll give it a try.

**Comment by RC-Robio** [comment]
I got in. Playing now. Make sure your mods on your pc are up to date.

**Comment by stephanepapin** [comment]
My fault don't check under DZSA

**Comment by stephanepapin** [comment]
Solved thank for help. issue is related to mod loading order
