### ISSUE TITLE
Script Errors in crash.txt

### ISSUE THREAD

**Issue by Instinkt-Servers** [salutesh/DayZ-Expansion-Scripts#17]
Error1:

Entity is already deleted
Class:      'ExpansionAirdropContainerBase'
Entity id:3068796

Function: 'OnUpdate'
Stack trace:
DayZExpansion/Scripts/4_World/dayzexpansion\entities\systems\airdrop\expansionairdropcontainerbase.c:204
scripts/3_Game/dayzgame.c:2331
DayZExpansion/Core/3_Game/dayzexpansion_core\dayzgame.c:203

Error2:

Entity is already deleted
Class:      'ExpansionAirdropContainerBase'
Entity id:3210527

Function: 'OnUpdate'
Stack trace:
DayZExpansion/Scripts/4_World/dayzexpansion\entities\systems\airdrop\expansionairdropcontainerbase.c:204
scripts/3_Game/dayzgame.c:2331
DayZExpansion/Core/3_Game/dayzexpansion_core\dayzgame.c:203

**Comment by LieutenantMaster** [comment]
Still looking into, I don't think the next update will fix it but it's still possible since we are touching a lot of airdrop related scripts with this update
