### ISSUE TITLE
Can't find variable 'm_CharClassNames'

### ISSUE THREAD

**Issue by kcwebdesign** [salutesh/DayZ-Expansion-Scripts#18]
After the last update I'm getting these errors and the game won't start. Have removed all MODs and reinstalled CF/Expansion only. New Missions folder. Still get the errors.

SCRIPT (E): @"DayZExpansion/Core/3_Game/dayzexpansion_core\dayzgame.c,44": Can't find variable 'm_CharClassNames'
SCRIPT (E): @"DayZExpansion/Core/3_Game/dayzexpansion_core\dayzgame.c,55": Can't find variable 'm_CharClassNames'
SCRIPT (E): @"DayZExpansion/Core/3_Game/dayzexpansion_core\settings\book\expansionbooksettings.c,275": Bad type 'JsonFileLoader'
SCRIPT (E): @"DayZExpansion/Core/3_Game/dayzexpansion_core\settings\map\expansionmapsettings.c,315": Bad type 'JsonFileLoader'
SCRIPT (E): @"DayZExpansion/Core/3_Game/dayzexpansion_core\settings\vehicles\expansionvehiclesettings.c,167": Bad type 'JsonFileLoader'
SCRIPT (E): @"DayZExpansion/Core/3_Game/dayzexpansion_core\settings\territory\expansionterritorysettings.c,141": Bad type 'JsonFileLoader'
SCRIPT (E): @"DayZExpansion/Core/3_Game/dayzexpansion_core\settings\debugging\expansiondebugsettings.c,143": Bad type 'JsonFileLoader'
SCRIPT (E): @"DayZExpansion/Core/3_Game/dayzexpansion_core\settings\spawning\expansionspawnsettings.c,165": Bad type 'JsonFileLoader'
SCRIPT (E): @"DayZExpansion/Core/3_Game/dayzexpansion_core\settings\raid\expansionraidsettings.c,169": Bad type 'JsonFileLoader'
SCRIPT (E): @"DayZExpansion/Scripts/3_Game/dayzexpansion\client\loadingscreen\expansionloadingscreen.c,45": Bad type 'JsonFileLoader'
SCRIPT (E): Can't compile "Game" script module!
DayZExpansion/Core/3_Game/dayzexpansion_core\dayzgame.c(44): Can't find variable 'm_CharClassNames'

**Comment by LieutenantMaster** [comment]
This error is due to a outdated dayz server. I assume you fixed it since, closing the ticket
