### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by NeTrox0** [salutesh/DayZ-Expansion-Scripts#19]
This client crash seems to be reocurring with trucks. not sure how interiors are connected to this.

**Crash Log**
01.01 2021 03:27:42
NULL pointer to instance
Class:      'ExpansionInteriorBuildingModule'
Function: 'ShouldIvySpawn'
Stack trace:
DayZExpansion/Scripts/4_World/dayzexpansion\classes\systems\mapping\expansioninteriorbuildingmodule.c:266
DayZExpansion/Scripts/4_World/dayzexpansion\entities\houses\buildingbase.c:343
DayZExpansion/Scripts/4_World/dayzexpansion\entities\houses\buildingbase.c:136
scripts/3_Game/dayzgame.c:2358
DayZExpansion/Core/3_Game/dayzexpansion_core\dayzgame.c:144

**From Script Log:**
DayZExpansion/Core/3_Game/dayzexpansion_core\dayzgame.c:144
SCRIPT       : 9
SCRIPT       : ==============================================WARNING==============================
SCRIPT       : [WARNING 2021-01-01 03:26:57] ASSERTION NULL
SCRIPT       : Do you see this message? Unless the time is within a second of the crash than this was not the cause.
SCRIPT    (E):    -- Stack trace --
SCRIPT    (E):    Assert_Log() JM/CF/Scripts/3_Game/communityframework\communityframework.c : 289
SCRIPT    (E):    Assert_Null() JM/CF/Scripts/3_Game/communityframework\communityframework.c : 315
SCRIPT    (E):    GetAuthenticatedPlayer() JM/COT/Scripts/4_World/communityonlinetools\entities\player\playerbase.c : 156
SCRIPT    (E):    OnUpdate() scripts/3_Game/dayzgame.c : 2358
SCRIPT    (E):    OnUpdate() DayZExpansion/Core/3_Game/dayzexpansion_core\dayzgame.c : 144
SCRIPT    (E):    -----------------
SCRIPT       : ===================================================================================
SCRIPT       : [emote] SurvivorM_Seth:015 play emote id=61 IH=SurrenderDummyItem:033561
SCRIPT       : + Truck_01_Covered<ae0a6ff0> add action: ActionOpenCarDoors<f1d5b570> input InteractActionInput
SCRIPT       : + Truck_01_Covered<ae0a6ff0> add action: ActionCloseCarDoors<f1d5ad50> input InteractActionInput
SCRIPT       : + Truck_01_Covered<ae0a6ff0> add action: ActionGetInTransport<f1c8dce0> input ContinuousInteractActionInput
SCRIPT       : + Truck_01_Covered<ae0a6ff0> add action: ActionSwitchLights<f1945da0> input ToggleLightsActionInput
SCRIPT       : + Truck_01_Covered<ae0a6ff0> add action: ExpansionActionPairKey<96d13420> input InteractActionInput
SCRIPT       : + Truck_01_Covered<ae0a6ff0> add action: ExpansionActionAdminUnpairKey<f1946160> input InteractActionInput
SCRIPT       : + Truck_01_Covered<ae0a6ff0> add action: ExpansionActionLockVehicle<f1946fc0> input InteractActionInput
SCRIPT       : + Truck_01_Covered<ae0a6ff0> add action: ExpansionActionUnlockVehicle<f19463e0> input InteractActionInput
SCRIPT       : + Truck_01_Covered<ae0a6ff0> add action: ActionSidePlateInteract<96d10da0> input InteractActionInput
SCRIPT       : + Truck_01_Covered<ae0a6ff0> add action: ActionDetachFromTarget_SpecificSlot_WoodenLogs<96d11530> input InteractActionInput
SCRIPT       : + Truck_01_Covered<ae0a6ff0> add action: ActionDetachFromTarget_SpecificSlot_WoodenPlanks<96d12660> input InteractActionInput
SCRIPT       : + Truck_01_Covered<ae0a6ff0> add action: ActionDetachFromTarget_SpecificSlot_MetalSheets<96d10c40> input InteractActionInput
SCRIPT       : + Truck_01_Covered<ae0a6ff0> add action: ActionDetachFromTarget_SpecificSlotsCategory_Barrel<96d115e0> input InteractActionInput
SCRIPT       : + Truck_01_Covered<ae0a6ff0> add action:  input InteractActionInput
SCRIPT    (E): NULL pointer to instance
Class:      'ExpansionInteriorBuildingModule'
Function: 'ShouldIvySpawn'
Stack trace:
DayZExpansion/Scripts/4_World/dayzexpansion\classes\systems\mapping\expansioninteriorbuildingmodule.c:266
DayZExpansion/Scripts/4_World/dayzexpansion\entities\houses\buildingbase.c:343
DayZExpansion/Scripts/4_World/dayzexpansion\entities\houses\buildingbase.c:136
scripts/3_Game/dayzgame.c:2358
DayZExpansion/Core/3_Game/dayzexpansion_core\dayzgame.c:144

**Comment by LieutenantMaster** [comment]
Hello, this errors should now be fixed with today update :)
