### ISSUE TITLE
Mapping lines from Offline to Expansion

### ISSUE THREAD

**Issue by tomaguy** [salutesh/DayZ-Expansion-Scripts#2]
Hello, when I export the mapping lines of the Offline, here is the structure:
SpawnObject ("Land_Village_HealthCare_Enoch," '8432.589844 362.160004 6573.120117', '-10.000002 0.00000 0.00000'); 

but the mod's  .MAP present themselves in this way :
ExpansionSign_Trader_Boats|14357.205078 4.374650 13234.102539|32.000004 0.000000 0.000000
Please, How Can I Fix that ? apart from changing everything by hand.
Thanx

**Comment by LieutenantMaster** [comment]
https://github.com/salutesh/DayZ-Expansion-Scripts/wiki/%5BServer-Hosting%5D-Updating-your-mapping-to-the-new-method
