### ISSUE TITLE
my server keeps loading forever

### ISSUE THREAD

**Issue by KineticClown56** [salutesh/DayZ-Expansion-Scripts#20]
before anyone says anything, yes i have read the wiki also ive followed the troubleshooting part aswell but for some reason the expansion wont let me use it at all and i dont know why is there anyone out there that can possibly help me if so add my discord 
KineticClown56#4119 ill have dms open so contact me i beg

**Comment by LieutenantMaster** [comment]
https://github.com/salutesh/DayZ-Expansion-Scripts/wiki/%5BServer-Hosting%5D-Setting-up-the-server#infinite-loading-screen-server-frozen
