### ISSUE TITLE
Player disconnect, heli stay in air , and other proposals

### ISSUE THREAD

**Issue by KOKOSTAS2001** [salutesh/DayZ-Expansion-Scripts#23]
when someone is inside a helicopter, and he quit for some reason, he spawn on terrain, or he dies. But the heli stays in air so it could be good if player disconnect from host the heli to go on the terrain...

Also it would be good if you remove physics from heli when none is in any seat so you can avoid heli do some weird things above the ground and much more efficient for performance. The idea is to stay on the ground with only collision and no drag or gravity or any other physics like a static object for example a cabinet .

Please consider when get out from heli to spawn the player above the ground and not this weird animation like he is hitting something . Raycast from left or right of heli where is the ground and spawn the player above it without hitting something or colliding with some colliders. Probably its easier if u make player avoid collision untill he touch the keyboard

**Comment by LieutenantMaster** [comment]
> But the heli stays in air so it could be good if player disconnect from host the heli to go on the terrain...
This was a feature in the past but broke at some point, we will add it back one day

> Also it would be good if you remove physics from heli when none is in any seat so you can avoid heli do some weird things above the ground and much more efficient for performance. The idea is to stay on the ground with only collision and no drag or gravity or any other physics like a static object for example a cabinet .
This issue will be solved with a long term solution we are working on to fight against the wierd quirks of the Enfusion Engine.

> Please consider when get out from heli to spawn the player above the ground and not this weird animation like he is hitting something . Raycast from left or right of heli where is the ground and spawn the player above it without hitting something or colliding with some colliders. Probably its easier if u make player avoid collision untill he touch the keyboard
This was due to a mix of a old dayz bug (now fixed with 1.11) and player attachment. So it should now be half be fixed. Not sure if we can safely fixed the second part since most of it is outside of range since it's mostly engine related stuff.

**Comment by KOKOSTAS2001** [comment]
something cause some problems with helis. I think due to wind because the helis at some point were jumping like crazy on the map
