### ISSUE TITLE
Building Shelters writes Crash log.

### ISSUE THREAD

**Issue by NeTrox0** [salutesh/DayZ-Expansion-Scripts#24]
When trying to build a shelter a null pointer exception is written in the crash log.

NULL pointer to instance
Class:      'Construction'
Function: 'CanBuildPart'
Stack trace:
DayZExpansion/Scripts/4_World/dayzexpansion\classes\basebuilding\construction.c:31
scripts/4_World/classes\basebuilding\construction.c:346
DayZExpansion/Scripts/4_World/dayzexpansion\classes\basebuilding\construction.c:110
scripts/4_World/classes\basebuilding\constructionactiondata.c:104
scripts/4_World/static\miscgameplayfunctions.c:737
scripts/4_World/classes\useractionscomponent\actions\interact\actionbuildshelter.c:101
scripts/4_World/classes\useractionscomponent\actionbase.c:662
scripts/4_World/classes\useractionscomponent\animatedactionbase.c:345
scripts/4_World/classes\useractionscomponent\actions\actioncontinuousbase.c:28

**Comment by LieutenantMaster** [comment]
Someone on your server used the "ExpansionAdminHammer" which is the cause of this NULL pointer. This is normal behavior since it's skipping a lot of steps to allow this tool to not require any ressources

**Comment by NeTrox0** [comment]
I see.. I'll have to check on my end then. I'll close this in the meantime.
