### ISSUE TITLE
Building Snap Points

### ISSUE THREAD

**Issue by petermh87** [salutesh/DayZ-Expansion-Scripts#25]
Hi,

Currently it is possible to snap a wall to the mid point of another wall to form a cross +.

However is it possible to snap a wall edge to the midpoint of another wall to form a t-shape T? (Likewise to snap a walls midpoint to the end of an existing wall to form a T)

If this is not possible, do you think it could be added during the next update? even if midpoint selection is a togglable hotkey as I believe it will make building bases a lot easier (especially custom shaped rooms within buildings).

See attached image where red line would indicate where a complete wall would snap to in this instance.
![Untitled](https://user-images.githubusercontent.com/63289593/106899787-aebf7f80-66ed-11eb-8d71-2a89cdfb03d7.jpg)

Thanks

**Comment by LieutenantMaster** [comment]
As explained earlier on discord, a basebuilding update is planned (won't be the next one).

We won't do exactly what you have in mind, but it will be possible to achieve a similar result in the futur
