### ISSUE TITLE
1 mod missing?

### ISSUE THREAD

**Issue by Naninou** [salutesh/DayZ-Expansion-Scripts#26]
![Sans titre](https://user-images.githubusercontent.com/78571033/106967898-2de1a180-6748-11eb-9bdf-6d706dcc2844.jpg)

Loged and played on the server, looked fine, but just in case i share it here.
Sorry for the trouble, and thanks for this amazing mod.

**Comment by Naninou** [comment]
![Sans titre](https://user-images.githubusercontent.com/78571033/106968195-ab0d1680-6748-11eb-808a-a0ab321df383.jpg)

**Comment by LieutenantMaster** [comment]
No idea, sorry

I'll get back to you if I get my info about it

**Comment by LieutenantMaster** [comment]
Still no reports of a similar issue on my side, any news with yours ?

**Comment by Naninou** [comment]
none sorry, i will close the issu, the game was working as intended anyway
