### ISSUE TITLE
 Bug report with an aircraft carrier

### ISSUE THREAD

**Issue by KremenUA** [salutesh/DayZ-Expansion-Scripts#27]
Hello friends, I have information about an error in the game that I met. On an aircraft carrier, when I go on it, the sound is like walking in the snow. I got up on the spot, and I'm starting to fall under the map, also such a mistake.
Secondly, there are places at some points on the ship got into the water. 
Thanks in advance, dear friends.
https://www.youtube.com/watch?v=jFzNheOC_8A

**Comment by LieutenantMaster** [comment]
Hello !

The missing collisions will be fixed in a futur vehicle update. As for the sounds I will see what I can do between 2 hotfix :)
