### ISSUE TITLE
UAZ power and gear issues

### ISSUE THREAD

**Issue by Mior** [salutesh/DayZ-Expansion-Scripts#29]
Hello there.

It seems there is issue with UAZ gearset, at least on server where I'm playing.
1. in UAZ gear 1 its hard to go uphill, engine is almost not going at all, really slowly.
2. when driving UAZ in gear 1 almost at end of gear and shift to gear 2, acceleration just drop. Gear range is too wide apart and vehicle have no acceleration in gear 2. Gear 3 is almost useless as maximum speed is reached in gear 2.

I think gear ratios need to be updated
https://github.com/salutesh/DayZ-Expansion-Scripts/blob/experimental/DayZExpansion/Vehicles/Ground/UAZ/config.cpp#L287

**Comment by LieutenantMaster** [comment]
Hello !

Already changed a bit for the next Expansion Update (really soon) :)
