### ISSUE TITLE
Disappearance of the territory after manual shutdown of the server

### ISSUE THREAD

**Issue by kubkadl** [salutesh/DayZ-Expansion-Scripts#30]
Hi, I have a problem that if I shut down the server hard, all the buildings (Territory) built since the last restart will disappear
if there is an automatic restart then this does not happen
does anyone know what it could be?
I didn't have this problem before the update

**Comment by LieutenantMaster** [comment]
The territory entity is a vanilla feature. I haven't seen any reports yet but this is probably because of something broken in your types.xml ?

I will get back to you if I learn more about it

**Comment by kubkadl** [comment]
SCRIPT    (E): JSON ERROR $CurrentDir:mpmissions\Expansion.ChernarusPlus\init.c:83
Maybe problem is this?

**Comment by LieutenantMaster** [comment]
Hello, sorry I don't usualy check this part of the wiki ^^'

"JSON ERROR" probably mean there is a issue with a json file, validate your json files or check for a crash log about a json setting file from a mod
