### ISSUE TITLE
Building's disappearing ( Player Buildings ) GunRack etc..except for tents...

### ISSUE THREAD

**Issue by worden38** [salutesh/DayZ-Expansion-Scripts#36]
I was wondering if you had any ideas as to why when I build a base it disappears upon server restart? This includes safes and gunracks..but the tents stay?

**Comment by LieutenantMaster** [comment]
Your mission is missing the config for this items or cannot read the file correctly. Verify your xml files or add the missing items into your types.xml (or use a expansion mission since they are already pre configured)
