### ISSUE TITLE
Corrupted String

### ISSUE THREAD

**Issue by GrandHunterMan** [salutesh/DayZ-Expansion-Scripts#5]
[crash_2020-09-13_15-23-30.log](https://github.com/salutesh/DayZ-Expansion-Scripts/files/5215025/crash_2020-09-13_15-23-30.log)

Vanilla items are being corrupted

**Comment by GrandHunterMan** [comment]
[crash.zip](https://github.com/salutesh/DayZ-Expansion-Scripts/files/5215054/crash.zip)


here's the rpt, script, dump and crash log for another time i tried to launch

**Comment by LieutenantMaster** [comment]
Hello,
Your "storage_x" is not compatible with the expansion storage format. Wipe this folder and your issue will be fixed. Make sure to run the server with expansion after the wipe
