### ISSUE TITLE
Active quests

### ISSUE THREAD

**Issue by tchao57** [salutesh/DayZ-Expansion-Scripts#51]
Hi,

the Mod is working but I only have 2 active quests. Kill 100 infected people and Find the treasure. I set "MaxActiveQuests": 6 in QuestSettings.json, delete the PlayerData file and restart the server, but always only 2 active Quests.

Any idea please?

Thanks.

**Comment by salutesh** [comment]
Pls report issues with our mods in our Discord or ask for help there.
