### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by 29emanuel29** [salutesh/DayZ-Expansion-Scripts#6]
I keep getting crashes:
This is client-side:

NULL pointer to instance
Class:      'Land_House_1W06'
Entity id:-9222369281586554190

Function: 'UnloadInterior'
Stack trace:
DayZExpansion/Scripts/4_World/dayzexpansion\entities\houses\buildingbase.c:272
DayZExpansion/Scripts/4_World/dayzexpansion\entities\houses\buildingbase.c:46

**Comment by InclementDab** [comment]
Fixed in https://github.com/salutesh/DayZ-Expansion/commit/601bdff0ccbecf77730613892cfe17c1e7a81a38

Should be fixed in next update
