### ISSUE TITLE
DeerIsle does not work & Community Online Tools causing crashes

### ISSUE THREAD

**Issue by 29emanuel29** [salutesh/DayZ-Expansion-Scripts#7]
Server won't boot up with DeerIsle as map.

As for Community Online Tools,
I have a lot of these:
Class: 'UIActionButton'
Function: 'Error'
Stack trace:
scripts/1_Core/proto\endebug.c:44
JM/COT/Scripts/5_Mission/communityonlinetools\gui\actions\uiactionbase.c:64
JM/COT/Scripts/5_Mission/communityonlinetools\modules\player\jmplayerform.c:454
JM/COT/Scripts/5_Mission/communityonlinetools\modules\player\jmplayerform.c:347
JM/COT/Scripts/5_Mission/communityonlinetools\modules\player\jmplayerform.c:215
JM/COT/Scripts/5_Mission/communityonlinetools\modules\player\jmplayerform.c:154
JM/COT/Scripts/4_World/communityonlinetools\classes\gui\jmformbase.c:27
JM/COT/Scripts/4_World/communityonlinetools\classes\gui\jmwindowbase.c:95
JM/COT/Scripts/4_World/communityonlinetools\classes\module\jmrenderablemodulebase.c:139
JM/COT/Scripts/4_World/communityonlinetools\classes\module\jmrenderablemodulebase.c:175
JM/COT/Scripts/4_World/communityonlinetools\classes\gui\jmcotsidebar.c:197

Is there any way we could replace Community Online Tools with something else? Kinda sad because it is such a good addon but if it causes crashes >__>

**Comment by LieutenantMaster** [comment]
Evening !

I just did some tests to see what was wrong. ExpansionCOM.DeerIsle have been fixed with the newer release: [https://github.com/ExpansionModTeam/DayZ-Expansion-Missions/releases/](https://github.com/ExpansionModTeam/DayZ-Expansion-Missions/releases/)
However the mission Expansion.DeerIsle seems to be working fine, make sure all the mods are up to date and you are not missing a mod.

**Comment by 29emanuel29** [comment]
So weird, for me, server-side I get this for DeerIsle:

```
Fault address:  826FC1F5 00:826FC1F5 Unknown module
file:     Expansion
world:    DeerIsle
Prev. code bytes: 2B D0 48 63 41 5C 48 8B 49 60 4D 63 DA 4C 23 D8
Fault code bytes: 4A 8B 0C D9 48 85 C9 74 31 4C 63 44 24 28 8B D3
=======================================================
note: Minidump has been generated into the file SC\DayZServer_x64_2020-09-15_06-50-15_2020-09-15_06-50-32.mdmp
```

**Comment by LieutenantMaster** [comment]
Sorry for the wait, I'm not used to have people reporting things here ^^'

You should check before this error and inside the other logs. This specific lines can't really tell what is wrong
