### ISSUE TITLE
Issue in the Init.c for Starting Gear.

### ISSUE THREAD

**Issue by ItzNathaniel** [salutesh/DayZ-Expansion-Scripts#8]
```c
if ( GetExpansionSettings() && GetExpansionSettings().GetSpawn() && GetExpansionSettings().GetSpawn().StartingGear.UseStartingGear )
{
	SetStartingGear(player);
}
else
{
// ...
}
```
Line 117 of init.c

The CustomClothing defined in SpawnSettings.json will only used if UseStartingGear = 1..
I'm reporting this because the Starting Gear should be optional. 

Fix:
Two functions: One for Clothing and one for Gear
Clothing will execute if UseCustomClothing is set to 1.
and gear will execure if UseStartingGear is set to 1.
Otherwise use default options.

**Comment by LieutenantMaster** [comment]
Thanks for the report, I'll look into it today !

**Comment by LieutenantMaster** [comment]
Hello again !

After double checking everything, nothing have to change it's working as intended.

If you don't want the starting gear just turn off UseStartingGear in SpawnSettings.json and will use instead the vanilla "loadout"
The "UseCustomClothing" will not get affected by this change.

https://i.imgur.com/w6ZEqCM.png
